services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d root"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: production
    ports:
      - 3000:8080
    depends_on:
      postgres:
        #condition: service_healthy
    enviroment:
      DB_HOST=localhost
      DB_USER=root
      DB_PASSWORLD=root
      DB_NAME=root
      DB_PORT=5432

# Para chamar o localhost --> http://localhost:3000/alunos